name: scrape-app

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - scrape-app
  scrape-service:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
    networks:
      - scrape-app
    ports:
      - 5000:5000
    depends_on:
      - mongo
  scrape-status-service:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
    networks:
      - scrape-app
    ports:
      - 5001:5001
    depends_on:
      - mongo
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./Client:/app
      - /app/node_modules
    networks:
      - scrape-app
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - scrape-service
volumes:
  mongo_data:
networks:
  scrape-app:
    driver: bridge
