name: scrape-app

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - scrape-app
  api:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
    networks:
      - scrape-app
    ports:
      - 5000:5000
volumes:
  mongo_data:
networks:
  scrape-app:
    driver: bridge
