name: scrape-app

services:
  api:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
    ports:
      - 5000:5000
