on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
     steps:
      # Checkout koda
      - name: Checkout code
        uses: actions/checkout@v2

      # Node postavke i instalacija zavisnosti
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        run: |
          cd Server
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd Client
          npm install

      # Pokretanje testova (ako su implementirani)
      - name: Run Backend Tests
        run: |
          cd Server
          npm test